### ISSUE TITLE
Create Chrysalis compatible Kaleidoscope sketch for Model 01

### ISSUE THREAD

**Issue by TheBaronHimself** [Lepidopterarium/Chrysalis#107]
Now that Chrysalis is starting to become more useful we should create a version of the default Kaleidoscope sketch that is fully compatible with Chrysalis and enables all functionality it provides. 
Basically something that would have the following tagline: "Upload this to your board and you're ready to use Chrysalis."

**Comment by jamesnvc** [comment]
Created https://github.com/Lepidopterarium/Model01-Firmware 

I also put a .hex as a [release on that repo](https://github.com/Lepidopterarium/Model01-Firmware/releases/tag/Chrysalis-v0.1) which should resolve #14.
