### ISSUE TITLE
Function/fn keys don't show up in the keymap editor

### ISSUE THREAD

**Issue by TheBaronHimself** [Lepidopterarium/Chrysalis#108]
The function/fn keys (palm keys) show up as unknown in the keymap editor. Also, as far as I can tell there is no way of mapping fn to keys, yet.

![screen shot 2017-11-05 at 12 53 08](https://user-images.githubusercontent.com/11179011/32414490-4ff2b0f2-c228-11e7-92e6-a6087f493a2b.png)

**Comment by jamesnvc** [comment]
Oh, I think that's because the keys.cljs doesn't know about the ShiftToLayer buttons...funnily enough, it does work with OneShot layers though
![screenshot-2017-11-05_12 48 33_est-05 00_1509904113](https://user-images.githubusercontent.com/38405/32417429-a8f325e8-c227-11e7-81db-338a9cab8416.png)

**Comment by jamesnvc** [comment]
Fixed by 172f16ea26728723c4de2f7dcba4f5c798f36edd
