### ISSUE TITLE
Insert Key Missing from UI

### ISSUE THREAD

**Issue by leavesofgrass** [Lepidopterarium/Chrysalis#117]
The Insert Key is not included in any of the categories provided by the UI.
The Insert Key is used as a modifier key for screen readers like JAWS and NVDA and is a critical key for custom keymaps for blind users.

**Comment by algernon** [comment]
I think including `insert` & `delete` in `Punctuation & Spaces` (which already includes `backspace`) would make sense.

**Comment by mattvenn** [comment]
I'd like to request arrow keys too please

**Comment by jamesnvc** [comment]
Added a "navigation" section with arrow keys, page up/down, home/end.

Maybe I should change "Punctuation & Spaces" to "Editing"? Would that make more sense?

**Comment by jamesnvc** [comment]
Addressed by by 70d886d3dc861a37aef8e29703903ebc263f8da8
