### ISSUE TITLE
Key code <-> representation <-> display

### ISSUE THREAD

**Issue by algernon** [Lepidopterarium/Chrysalis#12]
For some components, like the layout editor and the REPL, we need a way to work with keys efficiently. Directly translating to keycodes would not be efficient, nor smart. So we need a way to take a keycode, and turn it into something Chrysalis can easily work with, and then turn it into another something we can put on the keymap SVG.

The middle one should be a structured representation, like `{"type": "TapDance", "number": 1}`, or `{"type": "DualUseModifier", "modifier": "Left Control", "key": "Z"}`. This would be done by the TapDance and DualUse plugins. The display plugin would turn these into something presentable in an SVG.

For this to work well, the keycode<->representation part must be pluggable. And the best would be, if the Chrysalis plugin would live in the same repo as the Kaleidoscope one, to make it easier to keep them in sync.

**Comment by mattvenn** [comment]
great idea. I can imagine some SVG graphics we can create for the key caps to show what plugins they are attached to. Perhaps the Kaleidoscope plugins can have an assets directory like the Chrysalis hardware. Then plugin authors could design their own icons.

**Comment by algernon** [comment]
That's kind of the idea yep! :)

**Comment by algernon** [comment]
So, we've been brainstorming with @TheBaronHimself on IRC, and so far, it seems the best way forward is to have a `keymap` object, which holds an array of `layer` objects, which in turn, holds an array of `key` objects. Layers and Keymaps can have other meta-data applied to them, like a name, for displaying purposes.

The key object would, in all cases, be an object that has the following properties:

```js
{"plugin": "OneShot",
 "role": "modifier",
 "key": "Left Control"}
```
The `plugin` is important, because we can use that information to look up data about the plugin, such as an icon, or other assets.

**Comment by algernon** [comment]
I've been mulling over how to do the keycode representation in a way that is displayable, and future proof. Currently, we have the HID-specified keycodes stored as:

```clojure
{:type :keyboard
 :usage :a}
```

This mirrors the HID spec, pretty much, but it isn't such a great way to represent keycodes... I want a representation that is easy to work with. Something that is mostly disconnected from how they are displayed (and in the long run, display would be made configurable).

So, how about:

```clojure
{:plugin :core
 :key :a}
{:plugin :core
 :key :keypad/0}
{:plugin :oneshot
 :type :modifier
 :key :left-control}
{:plugin :dualuse
 :type :modifier
 :key :a
 :modifier :left-control}
{:plugin :leader
 :index 0}
```

We would have a `key-display` multimethod that would attempt to translate these to displayable strings, `code->key` to translate 16-bit keycode to the above representation, `key->code` for the other way - all of these multimethods. Though, `code->key` may need some trickery to support ranges... may end up being something else than a multimethod. Perhaps an atom that has a range to parser mapping...

Then there are things like the leader example above, where the keycode alone does not tell us much. In the long run, we want to be able to allow users to give names here, so user settings will have to have an overlay we can merge with the parsed codes, to give them more meaning.

I hope to have an API and an example or two implemented over the weekend, to make things clearer.
