### ISSUE TITLE
Clean up Model 01 SVG

### ISSUE THREAD

**Issue by TheBaronHimself** [Lepidopterarium/Chrysalis#61]
This SVG was created for a dirty hack so it's pretty messy. It should be cleaned up. I'll take care of it.

**Comment by jamesnvc** [comment]
Is this addressed by https://github.com/Lepidopterarium/Chrysalis/commit/a39df676c7fc0189f4fca0f385243d56484c6d03?

**Comment by TheBaronHimself** [comment]
I think it's been addressed even earlier. This can be closed. Thanks for reminding me.
