### ISSUE TITLE
led: Finish the import/export functionality

### ISSUE THREAD

**Issue by algernon** [Lepidopterarium/Chrysalis#69]
The exported JSON should be tied to a product, so we can warn the user if they try to import a theme made for a different device.

**Comment by TheBaronHimself** [comment]
Has this been addressed, or why did you close it, @jamesnvc?

**Comment by jamesnvc** [comment]
@TheBaronHimself closed this one & opened #119 instead, since the title of this issue, about import/export is working, but Algernon's comment about tying the export to a particular keyboard deserves a more specific issue, I thought.
