### ISSUE TITLE
Check SVG tags (--> viewBox correct?)

### ISSUE THREAD

**Issue by TheBaronHimself** [Lepidopterarium/Chrysalis#72]
I seem to have exported the Model01 SVG as the whole document as opposed to restricting it to the actual elements. I should make sure that none of our SVGs have useless whitespace around their graphical content and make sure that everything is scaled and centred correctly.

**Comment by jamesnvc** [comment]
I think this is good now, can we close it?

**Comment by TheBaronHimself** [comment]
I think we can close this, yes. I'm planning to get started revising the design soon. Similar issues may occur, but we'll take care of it as it happens.
