### ISSUE TITLE
led: Migrate to a palette based setup

### ISSUE THREAD

**Issue by algernon** [Lepidopterarium/Chrysalis#87]
Now that `FingerPainter` and `Colormap` share a palette, the LED theme editor should be migrated to support editing the palette, the current theme, and a Colormap too.

As a first step, lets just migrate to using a palette, but still calling `led.theme` under the hood.

**Comment by jamesnvc** [comment]
@algernon would you be able to clarify this one a little bit for posterity? I see how the old LEDControl method worked by just sending RGB colours for each key; is the idea to instead change the palette that the other plugins use, and then I guess also support the Colormap plugin?  What is the reason for moving away from the LEDControl method?

**Comment by jamesnvc** [comment]
I guess the palettes could be smaller, because they'd just be an index into the palette instead of an RGB triple.  That plus supporting other plugins like FingerPainter?

**Comment by algernon** [comment]
The main reason for moving to a palette-based setup was two-fold: to save space (considerable space, from three bytes per LED, we are down to one byte per two keys), and to be able to share a palette. The LEDControl method is still available, mind you, it would just feel inconsistent if we'd have two LED theme editors (one for Colormap & the like, another for raw cRGB).

For comparison, Colormap used 192 bytes per layer, but uses only 32 now with the palette based setup. When we have only 1k of EEPROM, this saving is HUGE.

And again, the old method still works, but supporting Colormap is - I think - a good goal, because that allows you to set up colors for all your layers, while the old method only allows setting up one theme, and requires host-side support to switch to a different one.

**Comment by jamesnvc** [comment]
Reading through the code, attempting to clarify my understanding of how this works: We use the palette focus hooks to set a palette, which is a set of sixteen colours. We can then use a plugin like Colormap to set a "theme", which is one particular arrangement of those sixteen colours on the keyboard. Is this accurate?

**Comment by algernon** [comment]
Yes.

**Comment by jamesnvc** [comment]
Addressed by ea4ad6b52aba718872d2a6f236e952f47ae373c1
