### ISSUE TITLE
Updating keymap fails on macOS/OS X

### ISSUE THREAD

**Issue by jamesnvc** [Lepidopterarium/Chrysalis#97]
Using the keymap editor seems to work under Linux (tested with Ubuntu 16.04), but causes a multi-minute freezing of the keyboard when pressing "Update" on OS X.

Some data points:
  - Default socket options on Linux have `cts: true`, but false on OS X. Changing this seemingly has no effect thought
  - Using the repl to incrementally send keymaps, it seems that the dramatic slowdown happens when sending more than two layers worth of keys (on a Model 01, so 128 keycodes)
  - When using the REPL to send keymaps, it seems like after sending a few smaller maps, I'm able to send the full keymap without freezing? Not 100% on reproducing this
  - I seem to be seeing some transparent keys being read as 0 instead of 0xffff. Not completely clear on the source of this though, will need more investigation

**Comment by algernon** [comment]
Can you try if the [this](https://github.com/keyboardio/Kaleidoscope-Focus/blob/master/extras/kaleidoscope-focus.py) tool works on the mac, using the same commands as in the Chrysalis REPL?

My gut tells me that we're looking at a flushing issue.

**Comment by jamesnvc** [comment]
Having some issues running the script under OS X; initially got a "no module serial" error, so I did a `pip install serial`, but then it gives "module serial has no attribute Serial" error. Is there a different serial module I should be installing?

**Comment by jamesnvc** [comment]
I  surmise I should install pySerial instead?

**Comment by algernon** [comment]
Oops, yes. You should install `pySerial`. Should have added a `requirements.txt` or something similar.

**Comment by jamesnvc** [comment]
Hm, so got it running, but I'm seeing the same behaviour; getting the keymap returns instantly, setting the new keymap freezes the keyboard for a few minutes. 

One possible workaround until we find the source: I'm trying [adding a focus hook to allow setting individual keys](https://github.com/jamesnvc/Kaleidoscope-EEPROM-Keymap/commit/5065230b9d08ffc82dc20122f6b2765c0dc456a6) for EEPROM-Keymapper; perhaps we could use that, since sending shorter amounts of data seems to work.

**Comment by algernon** [comment]
Another option would be to send one layer at a time, perhaps?

This is increasingly looking like a buffering issue.

**Comment by jamesnvc** [comment]
yeah...in either case though, we'd need to change how the EEPROM plugin works, since the current setup doesn't allow for skipping over any keys, hence sending everything at once.

**Comment by algernon** [comment]
Indeed. Just trying to optimize it a bit.

In the long run, I'd also like to figure out why it can't send the whole thing on Mac. But an alternative way that doesn't trigger the same issue is a good thing in any case.

**Comment by jamesnvc** [comment]
I can submit a PR to EEPROM-Keymapper to let it accept individual layers.

**Comment by algernon** [comment]
Please do.

**Comment by mattvenn** [comment]
I'm with Gergely on this. If I have some time next week I can look into what's happening at the electrical/protocol layer. I had some similar issues on linux and it seemed like it was the firmware getting stuck waiting for a new line character.

**Comment by jamesnvc** [comment]
Okay! It looks like the workaround works; I was able to upload a keymap on OS X and have the keyboard immediately respond & continue working.

This requires the newest version of Kaleidoscope-EEPROM-Keymap and adding `Focus.addHook(FOCUS_HOOK_KEYMAP_LAYER);` to the keyboard sketch.

**Comment by jamesnvc** [comment]
Still needs testing for other layers (only tried changing a key on the first layer), but it should work...I will hopefully get to that testing later today.

**Comment by jamesnvc** [comment]
Resolved by https://github.com/Lepidopterarium/Chrysalis/pull/99
