### ISSUE TITLE
Chrysalis has not yet published a Code of Conduct.

### ISSUE THREAD

**Issue by obra** [Lepidopterarium/Chrysalis#98]
Kaleidoscope has this CoC: https://github.com/keyboardio/Kaleidoscope/blob/master/CODE_OF_CONDUCT.md

I know that while Chrysalis started out as a tool for Kaleidoscope, there is some desire for it not to be _limited_ to Kaleidoscope.

I'd encourage the folks working on Chrysalis to make a conscious choice to pick and publish an open and inclusive code of conduct.

**Comment by algernon** [comment]
I usually picked the same CoC for my projects, so I'd propose we pick it for Chrysalis too.

**Comment by TheBaronHimself** [comment]
@obra: Should be create a chryaslis@kayboard.io email alias? If not, I'd be happy to just put my email down.

What do you think?

**Comment by algernon** [comment]
I can provide @madhouse-project.org, @5ms.in aliases if need be, or any subdomain of these.

**Comment by TheBaronHimself** [comment]
@obra: Fine by me :).

**Comment by TheBaronHimself** [comment]
Used Jesse's email and merged it.
